In [82]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
# Đọc dữ liệu từ iris.csv vào dataframe
iris_df = pd.read_csv("IRIS.csv")
iris_df_train, iris_df_test = train_test_split(iris_df,test_size=0.2,random_state=0)
iris_train = iris_df_train[iris_df_train.columns[0:4]]
iris_test = iris_df_test[iris_df_test.columns[0:4]]
iris_test

sepal_length  sepal_width  petal_length  petal_width
114           5.8          2.8           5.1          2.4
62            6.0          2.2           4.0          1.0
33            5.5          4.2           1.4          0.2
107           7.3          2.9           6.3          1.8
7             5.0          3.4           1.5          0.2
100           6.3          3.3           6.0          2.5
40            5.0          3.5           1.3          0.3
86            6.7          3.1           4.7          1.5
76            6.8          2.8           4.8          1.4
71            6.1          2.8           4.0          1.3
134           6.1          2.6           5.6          1.4
51            6.4          3.2           4.5          1.5
73            6.1          2.8           4.7          1.2
54            6.5          2.8           4.6          1.5
63            6.1          2.9           4.7          1.4
37            4.9          3.1           1.5          0.1
78            6.0          2.9           4.5          1.5
90            5.5          2.6           4.4          1.2
45            4.8          3.0           1.4          0.3
16            5.4          3.9           1.3          0.4
121           5.6          2.8           4.9          2.0
66            5.6          3.0           4.5          1.5
24            4.8          3.4           1.9          0.2
8             4.4          2.9           1.4          0.2
126           6.2          2.8           4.8          1.8
22            4.6          3.6           1.0          0.2
44            5.1          3.8           1.9          0.4
97            6.2          2.9           4.3          1.3
93            5.0          2.3           3.3          1.0
26            5.0          3.4           1.6          0.4

In [83]:
# gán số cụm
kmeans = KMeans(n_clusters=3)

# Áp dụng thuật toán KMeans để tìm ra các cụm
kmeans.fit(iris_train)

D:\anaconda\envs\chien\lib\site-packages\sklearn\cluster\_kmeans.py:1334: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


KMeans(n_clusters=3)

In [84]:

labels = kmeans.labels_
print(labels)

center = kmeans.cluster_centers_
print(center)

[2 1 0 1 2 1 0 1 1 1 2 0 2 0 0 1 2 2 1 2 1 2 1 1 1 1 1 1 2 2 1 0 1 1 1 1 1
 2 0 0 2 1 0 0 2 0 1 1 0 1 2 1 0 2 2 2 2 0 0 2 2 0 2 0 1 2 0 0 2 0 0 0 1 2
 2 0 0 0 1 1 0 0 1 0 2 1 2 1 0 1 0 2 0 0 2 0 2 1 1 1 2 2 1 2 0 1 2 1 0 1 1
 1 1 0 0 0 2 1 2 0]
[[5.02051282 3.4025641  1.46153846 0.23846154]
 [5.82888889 2.72222222 4.35333333 1.42222222]
 [6.87777778 3.08888889 5.69444444 2.06666667]]


In [90]:
from sklearn.metrics import accuracy_score
iris_setosa=iris_df_train.loc[iris_df_train["species"]=="Iris-setosa"]
iris_virginica=iris_df_train.loc[iris_df_train["species"]=="Iris-virginica"]
iris_versicolor=iris_df_train.loc[iris_df_train["species"]=="Iris-versicolor"]

species_map = {'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}
species_array = iris_df_train['species'].map(species_map).values
species_array

accuracy_score(labels, species_array.T)

0.8833333333333333

In [87]:
# gán số cụm
kmeans_test = KMeans(n_clusters=3)

# Áp dụng thuật toán KMeans để tìm ra các cụm
kmeans_test.fit(iris_test)

D:\anaconda\envs\chien\lib\site-packages\sklearn\cluster\_kmeans.py:1334: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


KMeans(n_clusters=3)

In [88]:

labels_test = kmeans_test.labels_
print(labels_test)

center_test = kmeans_test.cluster_centers_
print(center_test)


[0 2 1 0 1 0 1 2 2 2 0 2 2 2 2 1 2 2 1 1 2 2 1 1 2 1 1 2 2 1]
[[6.375      2.9        5.75       2.025     ]
 [4.95454545 3.47272727 1.47272727 0.26363636]
 [6.05333333 2.79333333 4.44666667 1.40666667]]


In [95]:
from sklearn.metrics import accuracy_score
iris_setosa_test=iris_df_test.loc[iris_df_test["species"]=="Iris-setosa"]
iris_virginica_test=iris_df_test.loc[iris_df_test["species"]=="Iris-virginica"]
iris_versicolor_test=iris_df_test.loc[iris_df_test["species"]=="Iris-versicolor"]

species_map_test = {'Iris-setosa': 1, 'Iris-versicolor': 2, 'Iris-virginica': 0}
species_array_test = iris_df_test['species'].map(species_map_test).values
species_array_test

accuracy_score(labels_test, species_array_test.T)

0.9333333333333333

In [89]:
# tập train đạt độ chính xác 88.33%
# tập test đạt độ chính xác là 93.33%